#!/bin/bash
set -euo pipefail

cd "$(dirname "$0")"

if [ -f /etc/apt/sources.list ]; then
    echo
    echo '📦 Updating apt package lists ...'
    sudo apt-get update

    echo
    echo '📦 Installing apt packages ...'
    grep -v '^#' ./apt-packages.txt | xargs sudo apt-get install -y
fi

echo
echo '📦 Installing Brew packages ...'
/home/linuxbrew/.linuxbrew/bin/brew bundle --no-lock --quiet

echo
echo '🔗 Linking dotfiles ...'
function link_dotfile() {
    src="$(realpath "$0")"
    dst="$HOME/$(realpath --relative-to=./dotfiles "$0")"
    echo "Linking $dst"
    mkdir -p "$(dirname "$dst")"
    ln -fs "$src" "$dst"
}
export -f link_dotfile
find ./dotfiles -type f -exec bash -c 'link_dotfile "$0"' {} \;

echo
echo '📄 Downloading global gitignore ...'
wget -qO ~/.gitignore_global 'https://raw.githubusercontent.com/github/gitignore/main/Global/Linux.gitignore'

source ~/.profile

echo
echo '🔌 Installing asdf plugins ...'
function install_asdf_plugin() {
    if ! asdf plugin list | grep -q "^$1$"; then
        echo "Installing $1"
        asdf plugin add "$@"
    else
        echo "Already installed $1"
    fi
}
install_asdf_plugin java
install_asdf_plugin nodejs
install_asdf_plugin python
install_asdf_plugin rust
install_asdf_plugin golang

echo
echo '🔌 Updating asdf plugins ...'
asdf plugin update --all

echo
echo '🔌 Installing asdf versions ...'
# try twice b/c https://github.com/asdf-vm/asdf-nodejs/pull/330
xargs -a ~/.tool-versions -n2 asdf install || xargs -a ~/.tool-versions -n2 asdf install

echo
echo '🎉 Done!'
